root_cause_analysis:
  alpha: 0.5
  init_x_bias: recon
  num_iter: 1000
  verbose: true
train:
  anomaly_score:
    name: rmse
  autoencoder:
    name: default
    params:
      batch_size: 128
      code_size: 2
      early_stopping: false
      epochs: 10
      layers:
      - 80
      - 40
      - 20
      learning_rate: 0.001
      loss_name: mean_squared_error
  data_clipping:
    lower_percentile: 0.001
    upper_percentile: 0.999
  data_preprocessor:
    steps:
    - name: column_selector
      params:
        features_to_exclude: []
        max_nan_frac_per_col: 0.2
      step_name: column_selector
    - name: low_unique_value_filter
      step_name: low_unique_value_filter
    - name: simple_imputer
      step_name: simple_imputer
    - name: standard_scaler
      step_name: standard_scaler
    - name: angle_transformer
      params:
        angles: []
      step_name: angle_transformer
  data_splitter:
    shuffle: true
    type: sklearn
    validation_split: 0.2
  threshold_selector:
    fit_on_val: true
    name: quantile
    params:
      quantile: 0.95
